version = 7

[[bot]]
name="Rookie Johnson"
ai="AlphabeticalBot"
icon="rookie.png"

[[bot]]
name="BtA Joe"
ai="StubbornBot"
icon="dad.png"

[[bot]]
name="The Gentleman"
ai="GentlemanBot"
icon="gentleman.png"

[[bot]]
name="Speeding Sam"
ai="Fast Tanyao"
icon="sam.png"

[[bot]]
name="Champion Junie"
ai="ThriceBot"
icon="junie.png"

[[bot]]
name="Bystander"
ai="AngryDiscardoBot"
icon="dudB.png"

[[bot]]
name="Mrs. Toto"
ai="TotoBot"
icon="dudC.png"

[[bot]]
name="You"
ai="Player"
icon="dudA.png"