version = 15

[[matches]]
stage = 0
completed = false
opponent = 'Rookie Johnson'
opponent_index = 2
ais = ['AngryDiscardoBot', 'AlphabeticalBot', 'AngryDiscardoBot']
intro=[
    'So you wanna take on the champs of Riichi Mahjong?',
    'Welcome to your first hurdle, the names Rookie Johnson. I may not be great, but you gotta get started somewhere.',
    "If you take me down, you'll be able to take on my mentor, Joe. He's better than average so you best be ready!",
    "Also, once you beat me I'll always be up for a rematch. You can find me at the freeplay table if you're looking for some practice."
]
on_player_wins="Hey you're not half bad! Congrats on the win."
on_player_loses="Hm, better luck next time. Riichi Mahjong is a tough game, stick with it and I'm sure you'll win a match against me!"
on_both_lose="Looks like we could both use some practice, the other folks at the table seemed to have a great game. Maybe next time!"

[[matches]]
stage = 1
completed = false
opponent = '"Better than Average" Joe'
opponent_index = 2
top_line_title = '"Better than Average"'
bottom_line_title = "Joe"
ais = ['AngryDiscardoBot', 'StubbornBot', 'AngryDiscardoBot']
intro=[
    "Hey! I'm Joe, congrats on beating my apprentice.",
    "You seem to be catching on pretty well to Riichi Mahjong, but let's see how you do against me!",
    "Nothing personal, but I gotta help you train for the champs ahead!",
    "For my games, I'll be sticking to a plan from turn one. Maybe use that to your advantage and play defensive around it!"
]
call_pon="Pon! I'll take that! Looks like I'm going for an Open Hand All Simples then..."
call_chi="Chi! I'll take that! Looks like I'm going for an Open Hand All Simples then..."
call_kan="Kan! I'll take that! Looks like I'm going for an Open Hand All Simples then..."
call_ron="Ron! Looks like I win this one!"
call_riichi="Riichi! Looks like my closed hand turned out pretty decent eh?"
on_player_wins=[
    "Congrats! I'm really proud of ya, that was a great game. The competition's fierce but I think you have a chance to be crowned champ!",
    "A little something about your next opponent, The Gentlemen. He'll never give a clue on what he's going for, and usually plays closed handed...",
    "Remember to keep an eye on his discards! It'll give you some insight into what tiles he's looking for."
]
on_player_loses="Hey, great effort! Maybe you'll win next game, I'm always excited to play another!"
on_both_lose="Looks like we could both use some practice, the other folks at the table seemed to have a great game. Maybe next time! Riichi Mahjong is a game of chance at the end of the day."

[[matches]]
stage = 2
completed = false
opponent = 'The Gentleman'
opponent_index = 2
ais = ['AngryDiscardoBot', 'GentlemanBot', 'AngryDiscardoBot']
intro=[
    "...",
    "....",
    ".....",
    "...A new challenger approaches...",
    "....",
    "...Let's get started..."
]
call_riichi='...Riichi...your end is near...'
call_ron='hm...ron.'
on_player_wins=[
    "...",
    "...Congrats, you've bested me with an incredible showing.",
    "Your next opponent will show even greater difficulty, be prepared."
]
on_player_loses="hm...maybe next time. My secrets? I'll never tell..."
on_both_lose="...sometimes, a rivalry see's a third challenger. Maybe next time..."

[[matches]]
stage = 3
completed = false
opponent = 'Speeding Sam'
opponent_index = 2
ais = ['GentlemanBot', 'Fast Tanyao', 'AngryDiscardoBot']
intro=[
    'Hey!',
    'HEY!',
    "THE NAMES SPEEDING SAM! I'M FAST",
    "I'M FURIOUS",
    "I'M HERE TO TAKE YOU DOWN",
    "LET'S GOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO"
]
on_player_wins=[
    "Wow! You're really something!",
    "You're onto your final opponent, the reigning champion Junie.",
    "She's real good, so get ready for some great matches!"
]
on_player_loses="HAHAAAA! I win this one! Maybe next time!"
on_both_lose="WHATTTTT! I was so sure one of us was going to win! Maybe next time..."

[[matches]]
stage = 4
completed = false
opponent = 'Champion Junie'
opponent_index = 2
ais = ['AngryDiscardoBot', 'ThriceBot', 'AngryDiscardoBot']
intro=[
    'Welcome, challenger.',
    "You've come quite far on your Riichi Mahjong journey.",
    "From all of us at the Royale, we are proud of your progress.",
    "I am your final challenge.",
    "As the current champion of the Riichi Royale, I accept your challenge!"
]
on_player_wins=[
    "You've done it. I knew you could!",
    "You have defeated all of the seat-holders of the Riichi Royale.",
    "And as such, you are the new reigning champion.",
    "Thank you so much for taking this journey and learning the wonderful game of Riichi Mahjong with us.",
    "On behalf of myself, and all the coordintors of the Riichi Royale, thank you for playing through our tournament and game!",
    "You can always find all of us current and now past seat-holders in the free play area. Come by sometime!"
]
on_player_loses=[
    "It seems I get to keep my current seat as champion of the Riichi Royale!",
    "Maybe next time! On your current journey you may continue to rematch me."
]
on_both_lose=[
    "Well this is awkward.",
    "Luckily, the others at the table are not on the current journey you are, and have not beaten any of the other seat-holders.",
    "As such, I will continue to keep my current seat as champion of the Riichi Royale!",
    "Come by again if you want a rematch."
]

